# Generated by Django 4.1 on 2022-08-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mediafiles')),
                ('qrcode', models.ImageField(upload_to='QrCode')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
