# Generated by Django 4.1 on 2022-08-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_useripaddress_remove_file_userip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useripaddress',
            old_name='userip',
            new_name='ipaddress',
        ),
    ]
